bot:
  token: ENC(1TLsc94VESsbG0AncvjDcgtOKIHyVBxLJ5Z08gmk78Gg8lNAXbtol5PB3/uT0xHzH+Is6+fcPfk=)
  username: itover9000_bot
  buttons:
    firstRow:
      - магн. буря
      - скучно!
      - курс валют
    secondRow:
      - текущая погода
      - анимация погоды

url:
  urlMainPageMeteoinfo: http://www.meteoinfo.by/radar/?q=UMMN&t=0
  urlToGifFile: http://www.meteoinfo.by/radar/UMMN/radar-map.gif
  gifFileNameFromMeteoinfo: radar-map.gif
  urlToBoredapi: https://www.boredapi.com/api/activity
  urlToGeomagneticSite: https://services.swpc.noaa.gov/json/planetary_k_index_1m.json

yandex:
  key: ENC(e5wacm2aD3v2KFIqpfQp1BjLvRU7aXNJO5KM5qYk4xdcAhNtCuBWhreiZQECYZXyVhk2pq0lBykClTMbl2+G+lB7VAbLTC1KdWgaaoYDo6fUMGt8njRtAVokQe0iicgU4P0vyscEvR4=)
  url: https://translate.yandex.net/api/v1.5/tr.json/translate?

currency:
  listCurrencies:
    # USD
    - 145
    # EUR
    - 292
    # RUB
    - 298
  urlApi: http://www.nbrb.by/API/ExRates/Rates/

map:
  x: 191
  y: 188
  width: 5
  height: 5
  message: Мозоли

spring:
  mail:
    host: smtp.yandex.ru
    emailSender: h.dabravolskay@yandex.ru
    password: ENC(zTpYFhURBaVZVCxrpPknlfQi3Kn9MEJ/)
    port: 465
    protocol: smtps
    emailRecipient: over9000@tut.by

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: over9000