bot:
  token: 884639123:AAGJUFOWF9hoyk4_qM7vNw3YFYHXpsxVAMA
  username: itover9000_bot

url:
  urlMainPageMeteoinfo: http://www.meteoinfo.by/radar/?q=UMMN&t=0
  urlToGifFile: http://www.meteoinfo.by/radar/UMMN/radar-map.gif
  gifFileNameFromMeteoinfo: radar-map.gif
  urlToBoredapi: https://www.boredapi.com/api/activity
  urlToGeomagneticSite: https://services.swpc.noaa.gov/json/planetary_k_index_1m.json

yandex:
  key: key=trnsl.1.1.20190511T083532Z.659a23627272fcf1.ab2b6c844422017a936d29c902783ebb3659700a
  url: https://translate.yandex.net/api/v1.5/tr.json/translate?

currency:
  listCurrencies:
    # USD
    - 145
    # EUR
    - 292
    # RUB
    - 298
  urlApi: http://www.nbrb.by/API/ExRates/Rates/

spring:
  mail:
    host: smtp.yandex.ru
    username: h.dabravolskay@yandex.ru
    password: tratata88
    port: 465
    protocol: smtps
    emailRecipient: over9000@tut.by